name: Rebuild Index
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v1
      - uses: Shirakumo/cl-markless@v1.2.9
        with:
          input: specification.mess
          output: specification.html
      - uses: Shirakumo/cl-markless@v1.2.9
        with:
          input: specification.mess
          output: specification.pdf
          format: latex
          styling: style.tex
      - shell: bash
        run: |
          mkdir -p /tmp/markless/
          cp -r specification.pdf style.css card.png index.html /tmp/markless/
          sed -e '/<main>/{r specification.html' -e 'd}' template.ctml > /tmp/markless/specification.html
      - name: Upload Github Pages Artefact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: /tmp/markless/
      - name: Write to Github Pages
        uses: actions/deploy-pages@v4
