name: Rebuild Index
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v1
      - uses: Shirakumo/cl-markless@v1.2.4
        with:
          input: specification.mess
          output: /tmp/markless/
      - shell: bash
        run: |
          cp style.css /tmp/markless/
          sed -e '/<main>/{r /tmp/markless/specification.html' -e 'd}' template.ctml > /tmp/markless/index.html
      - name: Upload Github Pages Artefact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: /tmp/markless/
      - name: Write to Github Pages
        uses: actions/deploy-pages@v4
